### ISSUE TITLE
TODO: style of the first page

### ISSUE THREAD

**Issue by josefpolasek** [josefpolasek/eshop#2]
- [ ] Navigation bar
- [ ] Side bar (categories)
- [ ] sort by bar
- [ ] card of products
- [ ] make the website responsive
